### ISSUE TITLE
Mcmmo not working on my 1.12 server

### ISSUE THREAD

**Issue by malbosia2013** [mcMMO-Dev/mcMMO-Classic#3]
here is a link to my logs:  https://mclo.gs/zdr0RTE

i do not know how to fix the issue, please help.

**Comment by nossr50** [comment]
This bug is caused by invalid values (or keys) that were left over from previous versions of mcMMO
Right now mcMMO does not fix this for you, a quick solution is to delete the .yml files
I'll be implementing a fix for this in the future

https://github.com/mcMMO-Dev/mcMMO-Classic/issues/2#issuecomment-451764004

**Comment by t00thpick1** [comment]
@malbosia2013 1.6 is not compatible with 1.12 unfortunately.  the Spigot/Bukkit API has been making a lot of incompatible changes in these major updates, and we have to choose to support one or the other.

**Comment by nossr50** [comment]
whoops didn't notice he was running 1.12 👍

**Comment by malbosia2013** [comment]
what version will work with 1.12?
